# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app import ai_conversation_pb2 as app_dot_ai__conversation__pb2


class AIConversationServiceStub(object):
    """AI Conversation Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/app.v1.AIConversationService/SendMessage',
                request_serializer=app_dot_ai__conversation__pb2.AIConversationRequest.SerializeToString,
                response_deserializer=app_dot_ai__conversation__pb2.AIConversationResponse.FromString,
                _registered_method=True)
        self.StreamConversation = channel.stream_stream(
                '/app.v1.AIConversationService/StreamConversation',
                request_serializer=app_dot_ai__conversation__pb2.AIConversationRequest.SerializeToString,
                response_deserializer=app_dot_ai__conversation__pb2.AIConversationResponse.FromString,
                _registered_method=True)


class AIConversationServiceServicer(object):
    """AI Conversation Service
    """

    def SendMessage(self, request, context):
        """Send a single message and get response (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamConversation(self, request_iterator, context):
        """Bidirectional streaming conversation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIConversationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=app_dot_ai__conversation__pb2.AIConversationRequest.FromString,
                    response_serializer=app_dot_ai__conversation__pb2.AIConversationResponse.SerializeToString,
            ),
            'StreamConversation': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamConversation,
                    request_deserializer=app_dot_ai__conversation__pb2.AIConversationRequest.FromString,
                    response_serializer=app_dot_ai__conversation__pb2.AIConversationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.v1.AIConversationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.v1.AIConversationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIConversationService(object):
    """AI Conversation Service
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.v1.AIConversationService/SendMessage',
            app_dot_ai__conversation__pb2.AIConversationRequest.SerializeToString,
            app_dot_ai__conversation__pb2.AIConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamConversation(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/app.v1.AIConversationService/StreamConversation',
            app_dot_ai__conversation__pb2.AIConversationRequest.SerializeToString,
            app_dot_ai__conversation__pb2.AIConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
