# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ai import ai_conversation_pb2 as ai_dot_ai__conversation__pb2


class AIConversationServiceStub(object):
    """AI Conversation Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_stream(
                '/ai.v1.AIConversationService/SendMessage',
                request_serializer=ai_dot_ai__conversation__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=ai_dot_ai__conversation__pb2.SendMessageResponse.FromString,
                _registered_method=True)


class AIConversationServiceServicer(object):
    """AI Conversation Service
    """

    def SendMessage(self, request, context):
        """Sends a message to the AI and receives a streaming response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIConversationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=ai_dot_ai__conversation__pb2.SendMessageRequest.FromString,
                    response_serializer=ai_dot_ai__conversation__pb2.SendMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.v1.AIConversationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.v1.AIConversationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIConversationService(object):
    """AI Conversation Service
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.v1.AIConversationService/SendMessage',
            ai_dot_ai__conversation__pb2.SendMessageRequest.SerializeToString,
            ai_dot_ai__conversation__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
