name: Feature Request
description: 新機能の要望を提案する
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        新機能の提案をありがとうございます。以下の情報を提供してください。

  - type: textarea
    id: problem
    attributes:
      label: 解決したい問題
      description: この機能要望に関連する問題や課題を説明してください
      placeholder: 現在どのような問題や不便さがありますか？
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: どのような機能や改善を提案しますか？
      placeholder: 具体的にどのような機能があれば問題が解決されますか？
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に検討した解決策があれば記載してください
      placeholder: 他にどのような方法を検討しましたか？
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の優先度はどの程度ですか？
      options:
        - 低 (あると便利)
        - 中 (重要)
        - 高 (必須)
    validations:
      required: true

  - type: checkboxes
    id: components
    attributes:
      label: 関連コンポーネント
      description: この機能要望が関連するコンポーネントを選択してください
      options:
        - label: AI Service (Python)
        - label: Frontend (Next.js)
        - label: Backend API (Go)
        - label: gRPC Protocol
        - label: Documentation
        - label: その他

  - type: textarea
    id: use_cases
    attributes:
      label: 使用例・ユースケース
      description: この機能がどのように使用されるか、具体的な例を記載してください
      placeholder: |
        例：
        1. ユーザーが...したい時
        2. システムが...する必要がある時
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ条件
      description: この機能が完成したと判断する条件を記載してください
      placeholder: |
        - [ ] ...ができる
        - [ ] ...が表示される
        - [ ] ...のエラーハンドリングができる
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 追加情報
      description: その他の関連情報、参考資料、スクリーンショットなどがあれば記載してください
    validations:
      required: false
